import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Roboto_Slab } from "next/font/google";

const inter = Inter({ subsets: ["latin"], weight: "400" });
const robotoSlab = Roboto_Slab({ subsets: ["latin"], weight: "700" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-br from-purple-100 via-blue-50 to-pink-100 `
          
        }
      >
        
          {children}
       
          
         
        
      </body>
    </html>
  );
}
